### ISSUE TITLE
Build a test-suite

### ISSUE THREAD

**Issue by ErikDeSmedt** [ark-bitcoin/bark#23]
We should have a testing-suite before using `bark` and `aspd` in production.
This is a tracking-issue that should help us to ensure we don't forget tests.

I will provide a checkmark if we have a passing test for the line.

## aspd

- **Wallet**
  - [ ] Fund the aspd bitcoin wallet
  - [ ] Query the balance of the wallet
- **Round transactions**
  - [ ] Swapping a vtxo
     - [ ] Swap a simple VTXO
     - [ ] Swap an ark out-of-round payment
  - [ ] Do not allow double-spending
    - [ ] VTXO cannot be used twice in the same round
    - [ ] VTXO can only be swapped in one round
    - [ ] VTXO cannot be swapped if the VTXO has been spent out-of-round 
    - [ ] No race conditions between out-of-round payments and in-round payments
  - [ ] Full rounds
    - [ ] Do not allow new VTXO's when a round is full
    - [ ] Provide propper error message when round is full
  - [ ] Starvation
    - [ ] A vtxo that refuses to sign is banned from that round
- **Out-of-round payments**
  - [ ] Preform an out-of-round transaction
    - [ ] Use a simple vtxo is an input
    - [ ] Spend an out-of-round payment again
  - [ ] Don't allow double-spending
    - [ ] Concurrent out-of-round transactions
    - [ ] Concurrent round-transactions
- **Claim Liquidity**
  - [ ] claim expired vtxo's
    - [ ] Claim the root of the tree
    - [ ] Collect all funds if a unilateral exit has occurred
  - [ ] Forfeited utxo
    - [ ] Respond to a client claiming a forfeited UTXO within `vtxo_exit_delta` blocks

## bark

- **Wallet**
  - [ ] Onchain payments increase balance
  - [ ] List onchain funds and ark-funds (including expiry times)
- **Round transactions**
  - [ ] Receive a round-transaction
    - [ ] Balance increased after receive
  - [ ] Send round-transaction
    - [ ] Balance decreased after send
    - [ ] Failed round or payment doesn't lock VTXO
- **Out-of-roudn transacton**
  - [ ] Recieve an out-of-round transaction
    - [ ] Balance increased
  - [ ] Send out-of-round transaction
    - [ ] Balance decreased
- **Unilteral exit**
  - [ ] Single user can perform unilateral exit
  - [ ] All users in a round can perform a unilateral exit

**Comment by stevenroose** [comment]
Moved to https://codeberg.org/ark-bitcoin/bark/issues/2.
